security:
  clientConfigurations:
    hvSryNDpvbNaeZcIm4teMjppye5VVDfwGne6YzRUs=:
      name: Test Logistics Inc
      accountId: 234555
      companyId: 123453

sDf5aYtyCLpeOgVjx3t5BMgr+gQx1iPdyBrwehumkrc=:
name: Pug Logisticts LLC
accountId: 45768594
companyId: 123456

