security:
  clientConfigurations:
    hvSryNDpvbNaeZcIm4teMjppye5VVDfwGne6YzRUs=:
      name: Test Logistics Inc
      accountId: 234555
      companyId: 123453
    FmZScieFIiR+OPD36uogs+/deAEUWCEJbUGesWimlhY=:
      name: Pug Logisticts LLC
      accountId: 45768594
      companyId: 123456
    qfr1SAr0KCeyRRqxKvht10YfuRzWktKlRR48buPHc=:
      name: New Logisticts LLC
      accountId: 45768594
      companyId: 123456

