security:
  clientConfigurations:
    hvSryNDpvbNaeZcIm4teMjppye5VVDfwGne6YzRUs=:
      name: Test Logistics Inc
      accountId: 234555
      companyId: 123453

Wr2HTVc+OTo6ZFeyaNbVesDCj2r8BRXgUw/nL5JQ64s=:
name: Pug Logisticts LLC
accountId: 45768594
companyId: 123456

