security:
  clientConfigurations:
    hvSryNDpvbNaeZcIm4teMjppye5VVDfwGne6YzRUs=:
      name: Test Logistics Inc
      accountId: 234555
      companyId: 123453
    FmZScieFIiR+OPD36uogs+/deAEUWCEJbUGesWimlhY=:
      name: Pug Logisticts LLC
      accountId: 45768594
      companyId: 123456
    Z52tQEqLHyI6aQIHFDKIuxLefsjEMr6FAmy93OX3Sw=:
      name: Meow Logistics LLC
      accountId: 457685
      companyId: 123456

