security:
  clientConfigurations:
    hvSryNDpvbNaeZcIm4teMjppye5VVDfwGne6YzRUs=:
      name: Test Logistics Inc
      accountId: 234555
      companyId: 123453

DEqhqcHQRNbglsBhciJMlJcHVafBwEL6ZWRe4NiuTk=:
  name: Pug Logistics LLC
  accountId: 85857
  companyId: 123456


    FlTVG9ZaOuFRTmiqJdvISFWsGic2hzXtsE403iGLeU=:
      name: Pug Logistics LLC
      accountId: 85857
      companyId: 123456
 w4HBHykIMX2n1V0N93wqwd6tXYTgJ32PGt9tjveorJ8=:
      name: Pug Logistics LLC
      accountId: 85857
      companyId: 123456