security:
  clientConfigurations:
    hvSryNDpvbNaeZcIm4teMjppye5VVDfwGne6YzRUs=:
      name: Test Logistics Inc
      accountId: 234555
      companyId: 123453

5GLKnSBZIVQB5h0IDLXNnLpSz9V3i/0+3sT8abrGxEY=:
name: Pug Logisticts LLC
accountId: 45768594
companyId: 123456

