security:
  clientConfigurations:
    hvSryNDpvbNaeZcIm4teMjppye5VVDfwGne6YzRUs=:
      name: Test Logistics Inc
      accountId: 234555
      companyId: 123453
    FmZScieFIiR+OPD36uogs+/deAEUWCEJbUGesWimlhY=:
      name: Pug Logisticts LLC
      accountId: 45768594
      companyId: 123456
    9Lc9IOGOCJjzf1oQy0R3rOLDNhJ0eum3mLfgx7pgtc=:
      name: Pug00 Logisticts LLC
      accountId: 45768594
      companyId: 123456

