security:
  clientConfigurations:
    hvSryNDpvbNaeZcIm4teMjppye5VVDfwGne6YzRUs=:
      name: Test Logistics Inc
      accountId: 234555
      companyId: 123453

    yZEJgWaoDWvCWuGXWpobyX6pan6hPZPBijWfd20BNA=:
      name: Pug Logistics LLC
      accountId: 85857
      companyId: 123456    HNB1e8TtljBFmt6IelBIOrkaEAxmYIITyiAxFs5Zw4=:
      name: Pug Logistics LLC
      accountId: 85857
      companyId: 123456