security:
  clientConfigurations:
    hvSryNDpvbNaeZcIm4teMjppye5VVDfwGne6YzRUs=:
      name: Test Logistics Inc
      accountId: 234555
      companyId: 123453
    FmZScieFIiR+OPD36uogs+/deAEUWCEJbUGesWimlhY=:
      name: Pug Logisticts LLC
      accountId: 45768594
      companyId: 123456
    trJ6inxY96nJScdERv6i7TkdEKQOKa2NcoKUaK9907A=:
      name: Pug096 Logisticts LLC
      accountId: 45768594
      companyId: undefined

