security:
  clientConfigurations:
    hvSryNDpvbNaeZcIm4teMjppye5VVDfwGne6YzRUs=:
      name: Test Logistics Inc
      accountId: 234555
      companyId: 123453
    FmZScieFIiR+OPD36uogs+/deAEUWCEJbUGesWimlhY=:
      name: Pug Logisticts LLC
      accountId: 45768594
      companyId: 123456
    ky4RArUSlSDpRvjck2x4Lg2BR7h49nNrSCb0ThRwcrw=:
      name: Meow Logisticts LLC
      accountId: 457685
      companyId: 123456

