security:
  clientConfigurations:
    hvSryNDpvbNaeZcIm4teMjppye5VVDfwGne6YzRUs=:
      name: Test Logistics Inc
      accountId: 234555
      companyId: 123453
    FmZScieFIiR+OPD36uogs+/deAEUWCEJbUGesWimlhY=:
      name: Pug Logisticts LLC
      accountId: 45768594
      companyId: 123456
    BLCSrEEw3mgY0V4hrQAlpZPhEgegKrKmQzQn4ijkI=:
      name: Pug Logisticts LLC
      accountId: 45768594
      companyId: 123456

