security:
  clientConfigurations:
    hvSryNDpvbNaeZcIm4teMjppye5VVDfwGne6YzRUs=:
      name: Test Logistics Inc
      accountId: 234555
      companyId: 123453
    FmZScieFIiR+OPD36uogs+/deAEUWCEJbUGesWimlhY=:
      name: Pug Logisticts LLC
      accountId: 45768594
      companyId: 123456
    3lW2SV7qjMRjUrA1QWnw9WAuNsBTBucXPxoFx945Y=:
      name: Pug096 Logisticts LLC
      accountId: 45768594
      companyId: 123456

