security:
  clientConfigurations:
    hvSryNDpvbNaeZcIm4teMjppye5VVDfwGne6YzRUs=:
      name: Test Logistics Inc
      accountId: 234555
      companyId: 123453
    FmZScieFIiR+OPD36uogs+/deAEUWCEJbUGesWimlhY=:
      name: Pug Logisticts LLC
      accountId: 45768594
      companyId: 123456
    woaZNkqmAv1qx48E2ya045W5Z8HdxGXrUOsV4Vc=:
      name: Pug096 Logisticts LLC
      accountId: 45768594
      companyId: 123456

