security:
  clientConfigurations:
    hvSryNDpvbNaeZcIm4teMjppye5VVDfwGne6YzRUs=:
      name: Test Logistics Inc
      accountId: 234555
      companyId: 123453

jjSMGd6ePyDShprQQpIXIChPA0k8MiKnwFz6eiHpTTk=:
name: Pug Logisticts LLC
accountId: 45768594
companyId: 123456

