security:
  clientConfigurations:
    hvSryNDpvbNaeZcIm4teMjppye5VVDfwGne6YzRUs=:
      name: Test Logistics Inc
      accountId: 234555
      companyId: 123453
    FmZScieFIiR+OPD36uogs+/deAEUWCEJbUGesWimlhY=:
      name: Pug Logisticts LLC
      accountId: 45768594
      companyId: 123456
    MrlxFmEo4occI0QNdFrEeD1cuaivO3iIRapZZzwXRI=:
      name: Pug007 Logisticts LLC
      accountId: 45768594
      companyId: 123456

