security:
  clientConfigurations:
    hvSryNDpvbNaeZcIm4teMjppye5VVDfwGne6YzRUs=:
      name: Test Logistics Inc
      accountId: 234555
      companyId: 123453


    ymXTiTH+cGIYjygVGmGA8gQOxHWv21aFjv/JVeeHOdM=:
      name: Pug Logisticts LLC
      accountId: 45768594
      companyId: 123456
