security:
  clientConfigurations:
    hvSryNDpvbNaeZcIm4teMjppye5VVDfwGne6YzRUs=:
      name: Test Logistics Inc
      accountId: 234555
      companyId: 123453

miUcdosCuVK6Wswbh0MbgGOw+HME+gvmr5uXduaFF80=:
name: Pug Logisticts LLC
accountId: 45768594
companyId: 123456

