security:
  clientConfigurations:
    hvSryNDpvbNaeZcIm4teMjppye5VVDfwGne6YzRUs=:
      name: Test Logistics Inc
      accountId: 234555
      companyId: 123453

S8aa8R2TbVb+HGOQhPBSTav9OkI23lgHzKla7MHBd8o=:
name: Pug Logisticts LLC
accountId: 45768594
companyId: 123456

