security:
  clientConfigurations:
    hvSryNDpvbNaeZcIm4teMjppye5VVDfwGne6YzRUs=:
      name: Test Logistics Inc
      accountId: 234555
      companyId: 123453

    fKxzrIKPK0t/L/9bjX6pGnD1F41wMEh7H/tjS7rlT3g=:
      name: Pug Logisticts LLC
      accountId: 45768594
      companyId: 123456

