security:
  clientConfigurations:
    hvSryNDpvbNaeZcIm4teMjppye5VVDfwGne6YzRUs=:
      name: Test Logistics Inc
      accountId: 234555
      companyId: 123453

D8kkAK0CCZnah5p8rKVlbbamaxIIfa5Y71aLgc8rMqc=:
      name: Pug Logisticts LLC
      accountId: 45768594
      companyId: 123456
