security:
  clientConfigurations:
    hvSryNDpvbNaeZcIm4teMjppye5VVDfwGne6YzRUs=:
      name: Test Logistics Inc
      accountId: 234555
      companyId: 123453

8QRSE8p0HHBCBUX+Q618fp2VibOthDqBx4q0go7oRG4=:
name: Pug Logisticts LLC
accountId: 45768594
companyId: 123456

